# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98f611e45407fb59a0fcfbf97ce0b61eb9496781e0cd40c0e89deee47cc386da0b0c1b81e680ecce0be96fa9e651b4909dab4c1dde9884eed2206962d37b531a

test:
  secret_key_base: d3289b263bb5d1ab78c0b7415681412e9bcab1f97248a31fb147b84f75588b37a1f85336ef1bda3256b2b52ebe8e1748fe90c1e20b958a513807569e0d7d3b5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
